function models = registry()
%REGISTRY Define the set of distributions to evaluate.
% Returns an array of structs with fields:
%   name, type ('cont'|'disc'), nParams, paramNames, support,
%   start(data), fit(data,start), pdf(x,theta), cdf(x,theta)

models = [ ...
    dists.normal(), ...
    dists.exponential(), ...
    dists.weibull(), ...
    dists.lognormal(), ...
    dists.gamma(), ...
    dists.logistic(), ...
    dists.rayleigh(), ...
    dists.studentt(), ...
    dists.chisquare(), ...
    dists.gumbel(), ...
    dists.loglogistic(), ...
    dists.inversegaussian(), ...
    dists.frechet(), ...
    dists.birnbaumsaunders(), ...
    dists.mixture_biexponential(), ...
    dists.mixture_biweibull(), ...
    dists.poisson(), ...
    dists.bernoulli(), ...
    dists.binomial(), ...
    dists.negativebinomial(), ...
    dists.geometric(), ...
    dists.hypergeometric(), ...
    dists.discrete_uniform(), ...
    dists.logarithmic(), ...
    dists.johnsonsb(), ...
    dists.johnsonsu() ...
];

end
